<?xml version = "1.0" encoding="UTF-8" standalone="yes" ?>

<!DOCTYPE textesJeu [
<!ELEMENT textesJeu (texte+)>
<!ELEMENT texte (contenu)>
<!ELEMENT contenu (#PCDATA)>
]>

<textesJeu>



	<texte id="boutonRepos">
	    <contenu>REPOS</contenu>
	</texte>
	<texte id="boutonInventaire">
	    <contenu>INVENTAIRE</contenu>
	</texte>
	<texte id="boutonMenu">
	    <contenu>MENU</contenu>
	</texte>
	<texte id="boutonInteraction">
	    <contenu>INTERACTION</contenu>
	</texte>	
	<texte id="energie">
		<contenu>Energie</contenu>
	</texte>
	<texte id="experience">
		<contenu>Experience</contenu>
	</texte>
	<texte id="niveau">
		<contenu>Niveau</contenu>
	</texte>
	<texte id="popupInteraction">
		<contenu>Interaction</contenu>
	</texte>
	<texte id="choixInteraction">
		<contenu>Veuillez choisir une interaction</contenu>
	</texte>
	<texte id="nothingToDoInteraction">
		<contenu>Il n'y a rien a faire ici !</contenu>
	</texte>
	<texte id="interactionModal">
		<contenu>Je suis une interaction modale</contenu>
	</texte>

</textesJeu>


