<?xml version = "1.0" encoding="UTF-8" standalone="yes" ?>

<!DOCTYPE textesJeu [
<!ELEMENT textesJeu (texte+)>
<!ELEMENT texte (contenu)>
<!ELEMENT contenu (#PCDATA)>
]>

<textesJeu>

	<texte id="boutonRepos">
	    <contenu>REST</contenu>
	</texte>
	<texte id="boutonInventaire">
	    <contenu>INVENTORY</contenu>
	</texte>
	<texte id="boutonMenu">
	    <contenu>MENU</contenu>
	</texte>
	<texte id="boutonInteraction">
	    <contenu>INTERACTION</contenu>
	</texte>
	<texte id="energie">
		<contenu>Energy</contenu>
	</texte>
	<texte id="experience">
		<contenu>Experience</contenu>
	</texte>
	<texte id="niveau">
		<contenu>Level</contenu>
	</texte>
	
	
</textesJeu>


