<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE classements_joueur [
<!ELEMENT classements_joueur (joueur+)>
<!ELEMENT joueur (nom, nb_ennemis_tues, distance, or, temps, score, difficulte)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT nb_ennemis_tues (#PCDATA)>
<!ELEMENT distance (#PCDATA)>
<!ELEMENT or (#PCDATA)>
<!ELEMENT temps (#PCDATA)>
<!ELEMENT score (#PCDATA)>
<!ELEMENT difficulte (#PCDATA)>
]>

<classements_joueur><joueur><nom>pseudoADefinirALaFin</nom><nb_ennemis_tues>0</nb_ennemis_tues><distance>0</distance><or>0</or><temps>0</temps><score>0</score><difficulte>difficulteDeTest</difficulte></joueur><joueur><nom>pseudoADefinirALaFin</nom><nb_ennemis_tues>0</nb_ennemis_tues><distance>0</distance><or>0</or><temps>0</temps><score>0</score><difficulte>difficulteDeTest</difficulte></joueur><joueur><nom>pseudoADefinirALaFin</nom><nb_ennemis_tues>0</nb_ennemis_tues><distance>0</distance><or>0</or><temps>0</temps><score>0</score><difficulte>difficulteDeTest</difficulte></joueur><joueur><nom>pseudoADefinirALaFin</nom><nb_ennemis_tues>0</nb_ennemis_tues><distance>0</distance><or>0</or><temps>0</temps><score>0</score><difficulte>Novice</difficulte></joueur><joueur><nom>pseudoADefinirALaFin</nom><nb_ennemis_tues>0</nb_ennemis_tues><distance>6</distance><or>0</or><temps>0</temps><score>1000</score><difficulte>difficulteDeTest</difficulte></joueur><joueur><nom>pseudoADefinirALaFin</nom><nb_ennemis_tues>0</nb_ennemis_tues><distance>6</distance><or>0</or><temps>0</temps><score>857</score><difficulte>difficulteDeTest</difficulte></joueur><joueur><nom>pseudoADefinirALaFin</nom><nb_ennemis_tues>0</nb_ennemis_tues><distance>6</distance><or>0</or><temps>0</temps><score>857</score><difficulte>difficulteDeTest</difficulte></joueur><joueur><nom>pseudoADefinirALaFin</nom><nb_ennemis_tues>0</nb_ennemis_tues><distance>6</distance><or>0</or><temps>0</temps><score>857</score><difficulte>difficulteDeTest</difficulte></joueur><joueur><nom>pseudoADefinirALaFin</nom><nb_ennemis_tues>0</nb_ennemis_tues><distance>6</distance><or>0</or><temps>0</temps><score>857</score><difficulte>difficulteDeTest</difficulte></joueur><joueur><nom>pseudoADefinirALaFin</nom><nb_ennemis_tues>0</nb_ennemis_tues><distance>6</distance><or>0</or><temps>0</temps><score>857</score><difficulte>difficulteDeTest</difficulte></joueur><joueur><nom>pseudoADefinirALaFin</nom><nb_ennemis_tues>0</nb_ennemis_tues><distance>6</distance><or>0</or><temps>0</temps><score>857</score><difficulte>difficulteDeTest</difficulte></joueur><joueur><nom>pseudoADefinirALaFin</nom><nb_ennemis_tues>0</nb_ennemis_tues><distance>6</distance><or>0</or><temps>0</temps><score>857</score><difficulte>difficulteDeTest</difficulte></joueur><joueur><nom>pseudoADefinirALaFin</nom><nb_ennemis_tues>0</nb_ennemis_tues><distance>6</distance><or>0</or><temps>0</temps><score>857</score><difficulte>difficulteDeTest</difficulte></joueur><joueur><nom>pseudoADefinirALaFin</nom><nb_ennemis_tues>0</nb_ennemis_tues><distance>6</distance><or>0</or><temps>0</temps><score>857</score><difficulte>difficulteDeTest</difficulte></joueur><joueur><nom>pseudoADefinirALaFin</nom><nb_ennemis_tues>0</nb_ennemis_tues><distance>6</distance><or>0</or><temps>0</temps><score>857</score><difficulte>difficulteDeTest</difficulte></joueur><joueur><nom>pseudoADefinirALaFin</nom><nb_ennemis_tues>0</nb_ennemis_tues><distance>6</distance><or>0</or><temps>0</temps><score>857</score><difficulte>difficulteDeTest</difficulte></joueur><joueur><nom>pseudoADefinirALaFin</nom><nb_ennemis_tues>0</nb_ennemis_tues><distance>6</distance><or>0</or><temps>0</temps><score>857</score><difficulte>difficulteDeTest</difficulte></joueur><joueur><nom>pseudoADefinirALaFin</nom><nb_ennemis_tues>0</nb_ennemis_tues><distance>6</distance><or>0</or><temps>0</temps><score>1000</score><difficulte>difficulteDeTest</difficulte></joueur><joueur><nom>pseudoADefinirALaFin</nom><nb_ennemis_tues>1</nb_ennemis_tues><distance>23</distance><or>0</or><temps>0</temps><score>1000</score><difficulte>difficulteDeTest</difficulte></joueur><joueur><nom>pseudoADefinirALaFin</nom><nb_ennemis_tues>5</nb_ennemis_tues><distance>49</distance><or>0</or><temps>0</temps><score>960</score><difficulte>Novice</difficulte></joueur><joueur><nom>pseudoADefinirALaFin</nom><nb_ennemis_tues>5</nb_ennemis_tues><distance>49</distance><or>0</or><temps>0</temps><score>960</score><difficulte>Novice</difficulte></joueur><joueur><nom>pseudoADefinirALaFin</nom><nb_ennemis_tues>2</nb_ennemis_tues><distance>34</distance><or>0</or><temps>0</temps><score>1000</score><difficulte>Novice</difficulte></joueur></classements_joueur>