<?xml version = "1.0" encoding="UTF-8" standalone="yes" ?>

<!DOCTYPE ref_graphiques [
<!ELEMENT ref_graphiques (reference+)>
<!ELEMENT reference (intitule_objet, img_ihm)>
<!ELEMENT intitule_objet (#PCDATA)>
<!ELEMENT img_ihm (#PCDATA)>
]>

<ref_graphiques>

<reference>
   <intitule_objet>joel</intitule_objet>
   <img_ihm>./img/jo.bmp</img_ihm>
</reference>

<reference>
   <intitule_objet>bucheron</intitule_objet>
   <img_ihm>./img/bucheron.bmp</img_ihm>
</reference>

</ref_graphiques>
